/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { GalleryItem } from "./models/gallery-item";
import { Map } from "ol";
export { GalleryItem } from "./models/gallery-item";
export { Map } from "ol";
export namespace Components {
    interface OagApplication {
        /**
          * @default false
         */
        "desktopOnly": boolean;
        /**
          * @default false
         */
        "desktopOptimized": boolean;
        /**
          * @default 1000
         */
        "loadedDelay": number;
    }
    interface OagAudio {
        /**
          * @default ''
         */
        "headline": string;
        /**
          * @default ''
         */
        "source": string;
    }
    interface OagChangelogEntry {
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "tags": string;
    }
    interface OagChangelogVersion {
        /**
          * @default ''
         */
        "date": string;
        /**
          * @default ''
         */
        "version": string;
    }
    interface OagCockpit {
        "close": () => Promise<void>;
        /**
          * @default 'Menü schließen'
         */
        "closeButton": string;
        /**
          * @default 'init'
         */
        "visible": boolean | 'init';
    }
    interface OagCockpitNavigationItem {
        "link"?: string;
        "number"?: string;
    }
    interface OagContent {
    }
    interface OagFigure {
        "caption": string;
        /**
          * @default 'inner'
         */
        "maxWidth": 'inner' | 'outer';
        "reference": string;
    }
    interface OagFontSize {
        /**
          * @default this.baseFontSize
         */
        "fontSize": number;
    }
    interface OagGallery {
        "images": Array<GalleryItem> | string;
        /**
          * @default false
         */
        "preview": boolean;
    }
    interface OagHero {
        "backgroundImage": string;
        "backgroundOverlay": string;
        "caption": string;
        "headline": string;
        /**
          * @default true
         */
        "scrollIndicator": boolean;
        /**
          * @default "Nach unten scrollen!"
         */
        "scrollIndicatorLabel": string;
    }
    interface OagHorizontalGallery {
        "images": Array<GalleryItem> | string;
    }
    interface OagImageComparison {
        /**
          * @default ''
         */
        "labelLeft": string;
        /**
          * @default ''
         */
        "labelRight": string;
        /**
          * @default undefined
         */
        "sliderIconPosition"?: any;
        /**
          * @default 50
         */
        "sliderPosition": number;
        /**
          * @default 4
         */
        "sliderWidth": number;
        /**
          * @default ''
         */
        "srcLeft": string;
        /**
          * @default ''
         */
        "srcRight": string;
    }
    interface OagImprint {
    }
    interface OagInformation {
    }
    interface OagLightbox {
        /**
          * @default ''
         */
        "caption": string;
    }
    interface OagLoading {
        /**
          * @default "Ortsarchiv Gemeinlebarn"
         */
        "label": string;
        /**
          * @default "Lade Projekt"
         */
        "text": string;
    }
    interface OagMap {
        /**
          * @default 'osm'
         */
        "backgroundLayer": 'orthophoto' | 'standard' | 'grau' | 'osm';
        /**
          * @default true
         */
        "disableTouchClass": boolean;
    }
    interface OagMenu {
        /**
          * @default 5
         */
        "fillAfterScrolledPosition": number;
    }
    interface OagMenuItem {
    }
    interface OagMisc {
        /**
          * @default ''
         */
        "image": string;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "tagline": string;
    }
    interface OagProject {
        /**
          * @default ''
         */
        "backgroundImage": string;
        /**
          * @default ''
         */
        "backgroundOverlay": string;
        /**
          * @default 'center center'
         */
        "backgroundPosition": string;
        /**
          * @default ''
         */
        "href": string;
        /**
          * @default 'Projekt ansehen'
         */
        "hrefLabel": string;
        /**
          * @default ''
         */
        "maintitle": string;
        /**
          * @default ''
         */
        "subtitle": string;
        /**
          * @default ''
         */
        "tag": string;
    }
    interface OagReference {
        /**
          * @default 'quelle'
         */
        "content": 'quelle' | 'literatur';
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "referenceCode": string;
    }
    interface OagScreenBackgroundLayerItem {
        /**
          * @default false
         */
        "active": boolean;
        "slug": string;
    }
    interface OagScreenContentLayerItem {
        /**
          * @default '#000000'
         */
        "color": string;
        /**
          * @default false
         */
        "hide": boolean;
        "slug": string;
    }
    interface OagScreenMap {
        /**
          * @default 'orthophoto'
         */
        "backgroundLayer": 'orthophoto' | 'standard' | 'grau' | 'osm';
        /**
          * @default true
         */
        "disableTouchClass": boolean;
        /**
          * @default 'init'
         */
        "visible": boolean | 'init';
    }
    interface OagTooltip {
        /**
          * @default 'none'
         */
        "icon": 'none' | 'information' | 'help' | 'person' | 'alert' | 'pin' | 'time';
        /**
          * @default false
         */
        "initialShow": boolean;
        "x": string;
        "y": string;
    }
}
export interface OagApplicationCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOagApplicationElement;
}
export interface OagMapCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOagMapElement;
}
export interface OagScreenContentLayerItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOagScreenContentLayerItemElement;
}
export interface OagScreenMapCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOagScreenMapElement;
}
declare global {
    interface HTMLOagApplicationElementEventMap {
        "loaded": void;
    }
    interface HTMLOagApplicationElement extends Components.OagApplication, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOagApplicationElementEventMap>(type: K, listener: (this: HTMLOagApplicationElement, ev: OagApplicationCustomEvent<HTMLOagApplicationElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOagApplicationElementEventMap>(type: K, listener: (this: HTMLOagApplicationElement, ev: OagApplicationCustomEvent<HTMLOagApplicationElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOagApplicationElement: {
        prototype: HTMLOagApplicationElement;
        new (): HTMLOagApplicationElement;
    };
    interface HTMLOagAudioElement extends Components.OagAudio, HTMLStencilElement {
    }
    var HTMLOagAudioElement: {
        prototype: HTMLOagAudioElement;
        new (): HTMLOagAudioElement;
    };
    interface HTMLOagChangelogEntryElement extends Components.OagChangelogEntry, HTMLStencilElement {
    }
    var HTMLOagChangelogEntryElement: {
        prototype: HTMLOagChangelogEntryElement;
        new (): HTMLOagChangelogEntryElement;
    };
    interface HTMLOagChangelogVersionElement extends Components.OagChangelogVersion, HTMLStencilElement {
    }
    var HTMLOagChangelogVersionElement: {
        prototype: HTMLOagChangelogVersionElement;
        new (): HTMLOagChangelogVersionElement;
    };
    interface HTMLOagCockpitElement extends Components.OagCockpit, HTMLStencilElement {
    }
    var HTMLOagCockpitElement: {
        prototype: HTMLOagCockpitElement;
        new (): HTMLOagCockpitElement;
    };
    interface HTMLOagCockpitNavigationItemElement extends Components.OagCockpitNavigationItem, HTMLStencilElement {
    }
    var HTMLOagCockpitNavigationItemElement: {
        prototype: HTMLOagCockpitNavigationItemElement;
        new (): HTMLOagCockpitNavigationItemElement;
    };
    interface HTMLOagContentElement extends Components.OagContent, HTMLStencilElement {
    }
    var HTMLOagContentElement: {
        prototype: HTMLOagContentElement;
        new (): HTMLOagContentElement;
    };
    interface HTMLOagFigureElement extends Components.OagFigure, HTMLStencilElement {
    }
    var HTMLOagFigureElement: {
        prototype: HTMLOagFigureElement;
        new (): HTMLOagFigureElement;
    };
    interface HTMLOagFontSizeElement extends Components.OagFontSize, HTMLStencilElement {
    }
    var HTMLOagFontSizeElement: {
        prototype: HTMLOagFontSizeElement;
        new (): HTMLOagFontSizeElement;
    };
    interface HTMLOagGalleryElement extends Components.OagGallery, HTMLStencilElement {
    }
    var HTMLOagGalleryElement: {
        prototype: HTMLOagGalleryElement;
        new (): HTMLOagGalleryElement;
    };
    interface HTMLOagHeroElement extends Components.OagHero, HTMLStencilElement {
    }
    var HTMLOagHeroElement: {
        prototype: HTMLOagHeroElement;
        new (): HTMLOagHeroElement;
    };
    interface HTMLOagHorizontalGalleryElement extends Components.OagHorizontalGallery, HTMLStencilElement {
    }
    var HTMLOagHorizontalGalleryElement: {
        prototype: HTMLOagHorizontalGalleryElement;
        new (): HTMLOagHorizontalGalleryElement;
    };
    interface HTMLOagImageComparisonElement extends Components.OagImageComparison, HTMLStencilElement {
    }
    var HTMLOagImageComparisonElement: {
        prototype: HTMLOagImageComparisonElement;
        new (): HTMLOagImageComparisonElement;
    };
    interface HTMLOagImprintElement extends Components.OagImprint, HTMLStencilElement {
    }
    var HTMLOagImprintElement: {
        prototype: HTMLOagImprintElement;
        new (): HTMLOagImprintElement;
    };
    interface HTMLOagInformationElement extends Components.OagInformation, HTMLStencilElement {
    }
    var HTMLOagInformationElement: {
        prototype: HTMLOagInformationElement;
        new (): HTMLOagInformationElement;
    };
    interface HTMLOagLightboxElement extends Components.OagLightbox, HTMLStencilElement {
    }
    var HTMLOagLightboxElement: {
        prototype: HTMLOagLightboxElement;
        new (): HTMLOagLightboxElement;
    };
    interface HTMLOagLoadingElement extends Components.OagLoading, HTMLStencilElement {
    }
    var HTMLOagLoadingElement: {
        prototype: HTMLOagLoadingElement;
        new (): HTMLOagLoadingElement;
    };
    interface HTMLOagMapElementEventMap {
        "readyMap": Map;
    }
    interface HTMLOagMapElement extends Components.OagMap, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOagMapElementEventMap>(type: K, listener: (this: HTMLOagMapElement, ev: OagMapCustomEvent<HTMLOagMapElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOagMapElementEventMap>(type: K, listener: (this: HTMLOagMapElement, ev: OagMapCustomEvent<HTMLOagMapElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOagMapElement: {
        prototype: HTMLOagMapElement;
        new (): HTMLOagMapElement;
    };
    interface HTMLOagMenuElement extends Components.OagMenu, HTMLStencilElement {
    }
    var HTMLOagMenuElement: {
        prototype: HTMLOagMenuElement;
        new (): HTMLOagMenuElement;
    };
    interface HTMLOagMenuItemElement extends Components.OagMenuItem, HTMLStencilElement {
    }
    var HTMLOagMenuItemElement: {
        prototype: HTMLOagMenuItemElement;
        new (): HTMLOagMenuItemElement;
    };
    interface HTMLOagMiscElement extends Components.OagMisc, HTMLStencilElement {
    }
    var HTMLOagMiscElement: {
        prototype: HTMLOagMiscElement;
        new (): HTMLOagMiscElement;
    };
    interface HTMLOagProjectElement extends Components.OagProject, HTMLStencilElement {
    }
    var HTMLOagProjectElement: {
        prototype: HTMLOagProjectElement;
        new (): HTMLOagProjectElement;
    };
    interface HTMLOagReferenceElement extends Components.OagReference, HTMLStencilElement {
    }
    var HTMLOagReferenceElement: {
        prototype: HTMLOagReferenceElement;
        new (): HTMLOagReferenceElement;
    };
    interface HTMLOagScreenBackgroundLayerItemElement extends Components.OagScreenBackgroundLayerItem, HTMLStencilElement {
    }
    var HTMLOagScreenBackgroundLayerItemElement: {
        prototype: HTMLOagScreenBackgroundLayerItemElement;
        new (): HTMLOagScreenBackgroundLayerItemElement;
    };
    interface HTMLOagScreenContentLayerItemElementEventMap {
        "showLayer": string;
        "hideLayer": string;
        "highlightLayer": string;
    }
    interface HTMLOagScreenContentLayerItemElement extends Components.OagScreenContentLayerItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOagScreenContentLayerItemElementEventMap>(type: K, listener: (this: HTMLOagScreenContentLayerItemElement, ev: OagScreenContentLayerItemCustomEvent<HTMLOagScreenContentLayerItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOagScreenContentLayerItemElementEventMap>(type: K, listener: (this: HTMLOagScreenContentLayerItemElement, ev: OagScreenContentLayerItemCustomEvent<HTMLOagScreenContentLayerItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOagScreenContentLayerItemElement: {
        prototype: HTMLOagScreenContentLayerItemElement;
        new (): HTMLOagScreenContentLayerItemElement;
    };
    interface HTMLOagScreenMapElementEventMap {
        "readyMap": Map;
    }
    interface HTMLOagScreenMapElement extends Components.OagScreenMap, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOagScreenMapElementEventMap>(type: K, listener: (this: HTMLOagScreenMapElement, ev: OagScreenMapCustomEvent<HTMLOagScreenMapElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOagScreenMapElementEventMap>(type: K, listener: (this: HTMLOagScreenMapElement, ev: OagScreenMapCustomEvent<HTMLOagScreenMapElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOagScreenMapElement: {
        prototype: HTMLOagScreenMapElement;
        new (): HTMLOagScreenMapElement;
    };
    interface HTMLOagTooltipElement extends Components.OagTooltip, HTMLStencilElement {
    }
    var HTMLOagTooltipElement: {
        prototype: HTMLOagTooltipElement;
        new (): HTMLOagTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "oag-application": HTMLOagApplicationElement;
        "oag-audio": HTMLOagAudioElement;
        "oag-changelog-entry": HTMLOagChangelogEntryElement;
        "oag-changelog-version": HTMLOagChangelogVersionElement;
        "oag-cockpit": HTMLOagCockpitElement;
        "oag-cockpit-navigation-item": HTMLOagCockpitNavigationItemElement;
        "oag-content": HTMLOagContentElement;
        "oag-figure": HTMLOagFigureElement;
        "oag-font-size": HTMLOagFontSizeElement;
        "oag-gallery": HTMLOagGalleryElement;
        "oag-hero": HTMLOagHeroElement;
        "oag-horizontal-gallery": HTMLOagHorizontalGalleryElement;
        "oag-image-comparison": HTMLOagImageComparisonElement;
        "oag-imprint": HTMLOagImprintElement;
        "oag-information": HTMLOagInformationElement;
        "oag-lightbox": HTMLOagLightboxElement;
        "oag-loading": HTMLOagLoadingElement;
        "oag-map": HTMLOagMapElement;
        "oag-menu": HTMLOagMenuElement;
        "oag-menu-item": HTMLOagMenuItemElement;
        "oag-misc": HTMLOagMiscElement;
        "oag-project": HTMLOagProjectElement;
        "oag-reference": HTMLOagReferenceElement;
        "oag-screen-background-layer-item": HTMLOagScreenBackgroundLayerItemElement;
        "oag-screen-content-layer-item": HTMLOagScreenContentLayerItemElement;
        "oag-screen-map": HTMLOagScreenMapElement;
        "oag-tooltip": HTMLOagTooltipElement;
    }
}
declare namespace LocalJSX {
    interface OagApplication {
        /**
          * @default false
         */
        "desktopOnly"?: boolean;
        /**
          * @default false
         */
        "desktopOptimized"?: boolean;
        /**
          * @default 1000
         */
        "loadedDelay"?: number;
        "onLoaded"?: (event: OagApplicationCustomEvent<void>) => void;
    }
    interface OagAudio {
        /**
          * @default ''
         */
        "headline"?: string;
        /**
          * @default ''
         */
        "source"?: string;
    }
    interface OagChangelogEntry {
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default ''
         */
        "tags"?: string;
    }
    interface OagChangelogVersion {
        /**
          * @default ''
         */
        "date"?: string;
        /**
          * @default ''
         */
        "version"?: string;
    }
    interface OagCockpit {
        /**
          * @default 'Menü schließen'
         */
        "closeButton"?: string;
        /**
          * @default 'init'
         */
        "visible"?: boolean | 'init';
    }
    interface OagCockpitNavigationItem {
        "link"?: string;
        "number"?: string;
    }
    interface OagContent {
    }
    interface OagFigure {
        "caption"?: string;
        /**
          * @default 'inner'
         */
        "maxWidth"?: 'inner' | 'outer';
        "reference"?: string;
    }
    interface OagFontSize {
        /**
          * @default this.baseFontSize
         */
        "fontSize"?: number;
    }
    interface OagGallery {
        "images"?: Array<GalleryItem> | string;
        /**
          * @default false
         */
        "preview"?: boolean;
    }
    interface OagHero {
        "backgroundImage"?: string;
        "backgroundOverlay"?: string;
        "caption"?: string;
        "headline"?: string;
        /**
          * @default true
         */
        "scrollIndicator"?: boolean;
        /**
          * @default "Nach unten scrollen!"
         */
        "scrollIndicatorLabel"?: string;
    }
    interface OagHorizontalGallery {
        "images"?: Array<GalleryItem> | string;
    }
    interface OagImageComparison {
        /**
          * @default ''
         */
        "labelLeft"?: string;
        /**
          * @default ''
         */
        "labelRight"?: string;
        /**
          * @default undefined
         */
        "sliderIconPosition"?: any;
        /**
          * @default 50
         */
        "sliderPosition"?: number;
        /**
          * @default 4
         */
        "sliderWidth"?: number;
        /**
          * @default ''
         */
        "srcLeft"?: string;
        /**
          * @default ''
         */
        "srcRight"?: string;
    }
    interface OagImprint {
    }
    interface OagInformation {
    }
    interface OagLightbox {
        /**
          * @default ''
         */
        "caption"?: string;
    }
    interface OagLoading {
        /**
          * @default "Ortsarchiv Gemeinlebarn"
         */
        "label"?: string;
        /**
          * @default "Lade Projekt"
         */
        "text"?: string;
    }
    interface OagMap {
        /**
          * @default 'osm'
         */
        "backgroundLayer"?: 'orthophoto' | 'standard' | 'grau' | 'osm';
        /**
          * @default true
         */
        "disableTouchClass"?: boolean;
        "onReadyMap"?: (event: OagMapCustomEvent<Map>) => void;
    }
    interface OagMenu {
        /**
          * @default 5
         */
        "fillAfterScrolledPosition"?: number;
    }
    interface OagMenuItem {
    }
    interface OagMisc {
        /**
          * @default ''
         */
        "image"?: string;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default ''
         */
        "tagline"?: string;
    }
    interface OagProject {
        /**
          * @default ''
         */
        "backgroundImage"?: string;
        /**
          * @default ''
         */
        "backgroundOverlay"?: string;
        /**
          * @default 'center center'
         */
        "backgroundPosition"?: string;
        /**
          * @default ''
         */
        "href"?: string;
        /**
          * @default 'Projekt ansehen'
         */
        "hrefLabel"?: string;
        /**
          * @default ''
         */
        "maintitle"?: string;
        /**
          * @default ''
         */
        "subtitle"?: string;
        /**
          * @default ''
         */
        "tag"?: string;
    }
    interface OagReference {
        /**
          * @default 'quelle'
         */
        "content"?: 'quelle' | 'literatur';
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default ''
         */
        "referenceCode"?: string;
    }
    interface OagScreenBackgroundLayerItem {
        /**
          * @default false
         */
        "active"?: boolean;
        "slug"?: string;
    }
    interface OagScreenContentLayerItem {
        /**
          * @default '#000000'
         */
        "color"?: string;
        /**
          * @default false
         */
        "hide"?: boolean;
        "onHideLayer"?: (event: OagScreenContentLayerItemCustomEvent<string>) => void;
        "onHighlightLayer"?: (event: OagScreenContentLayerItemCustomEvent<string>) => void;
        "onShowLayer"?: (event: OagScreenContentLayerItemCustomEvent<string>) => void;
        "slug"?: string;
    }
    interface OagScreenMap {
        /**
          * @default 'orthophoto'
         */
        "backgroundLayer"?: 'orthophoto' | 'standard' | 'grau' | 'osm';
        /**
          * @default true
         */
        "disableTouchClass"?: boolean;
        "onReadyMap"?: (event: OagScreenMapCustomEvent<Map>) => void;
        /**
          * @default 'init'
         */
        "visible"?: boolean | 'init';
    }
    interface OagTooltip {
        /**
          * @default 'none'
         */
        "icon"?: 'none' | 'information' | 'help' | 'person' | 'alert' | 'pin' | 'time';
        /**
          * @default false
         */
        "initialShow"?: boolean;
        "x"?: string;
        "y"?: string;
    }

    interface OagApplicationAttributes {
        "desktopOptimized": boolean;
        "desktopOnly": boolean;
        "loadedDelay": number;
    }
    interface OagAudioAttributes {
        "headline": string;
        "source": string;
    }
    interface OagChangelogEntryAttributes {
        "label": string;
        "tags": string;
    }
    interface OagChangelogVersionAttributes {
        "date": string;
        "version": string;
    }
    interface OagCockpitAttributes {
        "visible": string;
        "closeButton": string;
    }
    interface OagCockpitNavigationItemAttributes {
        "number": string;
        "link": string;
    }
    interface OagFigureAttributes {
        "maxWidth": 'inner' | 'outer';
        "caption": string;
        "reference": string;
    }
    interface OagFontSizeAttributes {
        "fontSize": number;
    }
    interface OagGalleryAttributes {
        "images": Array<GalleryItem> | string;
        "preview": boolean;
    }
    interface OagHeroAttributes {
        "headline": string;
        "caption": string;
        "backgroundImage": string;
        "backgroundOverlay": string;
        "scrollIndicator": boolean;
        "scrollIndicatorLabel": string;
    }
    interface OagHorizontalGalleryAttributes {
        "images": Array<GalleryItem> | string;
    }
    interface OagImageComparisonAttributes {
        "srcLeft": string;
        "srcRight": string;
        "labelLeft": string;
        "labelRight": string;
        "sliderWidth": number;
        "sliderIconPosition": string;
        "sliderPosition": number;
    }
    interface OagLightboxAttributes {
        "caption": string;
    }
    interface OagLoadingAttributes {
        "label": string;
        "text": string;
    }
    interface OagMapAttributes {
        "backgroundLayer": 'orthophoto' | 'standard' | 'grau' | 'osm';
        "disableTouchClass": boolean;
    }
    interface OagMenuAttributes {
        "fillAfterScrolledPosition": number;
    }
    interface OagMiscAttributes {
        "image": string;
        "label": string;
        "tagline": string;
    }
    interface OagProjectAttributes {
        "maintitle": string;
        "subtitle": string;
        "href": string;
        "hrefLabel": string;
        "backgroundImage": string;
        "backgroundOverlay": string;
        "backgroundPosition": string;
        "tag": string;
    }
    interface OagReferenceAttributes {
        "label": string;
        "referenceCode": string;
        "content": 'quelle' | 'literatur';
    }
    interface OagScreenBackgroundLayerItemAttributes {
        "slug": string;
        "active": boolean;
    }
    interface OagScreenContentLayerItemAttributes {
        "slug": string;
        "color": string;
        "hide": boolean;
    }
    interface OagScreenMapAttributes {
        "visible": string;
        "disableTouchClass": boolean;
        "backgroundLayer": 'orthophoto' | 'standard' | 'grau' | 'osm';
    }
    interface OagTooltipAttributes {
        "initialShow": boolean;
        "x": string;
        "y": string;
        "icon": 'none' | 'information' | 'help' | 'person' | 'alert' | 'pin' | 'time';
    }

    interface IntrinsicElements {
        "oag-application": Omit<OagApplication, keyof OagApplicationAttributes> & { [K in keyof OagApplication & keyof OagApplicationAttributes]?: OagApplication[K] } & { [K in keyof OagApplication & keyof OagApplicationAttributes as `attr:${K}`]?: OagApplicationAttributes[K] } & { [K in keyof OagApplication & keyof OagApplicationAttributes as `prop:${K}`]?: OagApplication[K] };
        "oag-audio": Omit<OagAudio, keyof OagAudioAttributes> & { [K in keyof OagAudio & keyof OagAudioAttributes]?: OagAudio[K] } & { [K in keyof OagAudio & keyof OagAudioAttributes as `attr:${K}`]?: OagAudioAttributes[K] } & { [K in keyof OagAudio & keyof OagAudioAttributes as `prop:${K}`]?: OagAudio[K] };
        "oag-changelog-entry": Omit<OagChangelogEntry, keyof OagChangelogEntryAttributes> & { [K in keyof OagChangelogEntry & keyof OagChangelogEntryAttributes]?: OagChangelogEntry[K] } & { [K in keyof OagChangelogEntry & keyof OagChangelogEntryAttributes as `attr:${K}`]?: OagChangelogEntryAttributes[K] } & { [K in keyof OagChangelogEntry & keyof OagChangelogEntryAttributes as `prop:${K}`]?: OagChangelogEntry[K] };
        "oag-changelog-version": Omit<OagChangelogVersion, keyof OagChangelogVersionAttributes> & { [K in keyof OagChangelogVersion & keyof OagChangelogVersionAttributes]?: OagChangelogVersion[K] } & { [K in keyof OagChangelogVersion & keyof OagChangelogVersionAttributes as `attr:${K}`]?: OagChangelogVersionAttributes[K] } & { [K in keyof OagChangelogVersion & keyof OagChangelogVersionAttributes as `prop:${K}`]?: OagChangelogVersion[K] };
        "oag-cockpit": Omit<OagCockpit, keyof OagCockpitAttributes> & { [K in keyof OagCockpit & keyof OagCockpitAttributes]?: OagCockpit[K] } & { [K in keyof OagCockpit & keyof OagCockpitAttributes as `attr:${K}`]?: OagCockpitAttributes[K] } & { [K in keyof OagCockpit & keyof OagCockpitAttributes as `prop:${K}`]?: OagCockpit[K] };
        "oag-cockpit-navigation-item": Omit<OagCockpitNavigationItem, keyof OagCockpitNavigationItemAttributes> & { [K in keyof OagCockpitNavigationItem & keyof OagCockpitNavigationItemAttributes]?: OagCockpitNavigationItem[K] } & { [K in keyof OagCockpitNavigationItem & keyof OagCockpitNavigationItemAttributes as `attr:${K}`]?: OagCockpitNavigationItemAttributes[K] } & { [K in keyof OagCockpitNavigationItem & keyof OagCockpitNavigationItemAttributes as `prop:${K}`]?: OagCockpitNavigationItem[K] };
        "oag-content": OagContent;
        "oag-figure": Omit<OagFigure, keyof OagFigureAttributes> & { [K in keyof OagFigure & keyof OagFigureAttributes]?: OagFigure[K] } & { [K in keyof OagFigure & keyof OagFigureAttributes as `attr:${K}`]?: OagFigureAttributes[K] } & { [K in keyof OagFigure & keyof OagFigureAttributes as `prop:${K}`]?: OagFigure[K] };
        "oag-font-size": Omit<OagFontSize, keyof OagFontSizeAttributes> & { [K in keyof OagFontSize & keyof OagFontSizeAttributes]?: OagFontSize[K] } & { [K in keyof OagFontSize & keyof OagFontSizeAttributes as `attr:${K}`]?: OagFontSizeAttributes[K] } & { [K in keyof OagFontSize & keyof OagFontSizeAttributes as `prop:${K}`]?: OagFontSize[K] };
        "oag-gallery": Omit<OagGallery, keyof OagGalleryAttributes> & { [K in keyof OagGallery & keyof OagGalleryAttributes]?: OagGallery[K] } & { [K in keyof OagGallery & keyof OagGalleryAttributes as `attr:${K}`]?: OagGalleryAttributes[K] } & { [K in keyof OagGallery & keyof OagGalleryAttributes as `prop:${K}`]?: OagGallery[K] };
        "oag-hero": Omit<OagHero, keyof OagHeroAttributes> & { [K in keyof OagHero & keyof OagHeroAttributes]?: OagHero[K] } & { [K in keyof OagHero & keyof OagHeroAttributes as `attr:${K}`]?: OagHeroAttributes[K] } & { [K in keyof OagHero & keyof OagHeroAttributes as `prop:${K}`]?: OagHero[K] };
        "oag-horizontal-gallery": Omit<OagHorizontalGallery, keyof OagHorizontalGalleryAttributes> & { [K in keyof OagHorizontalGallery & keyof OagHorizontalGalleryAttributes]?: OagHorizontalGallery[K] } & { [K in keyof OagHorizontalGallery & keyof OagHorizontalGalleryAttributes as `attr:${K}`]?: OagHorizontalGalleryAttributes[K] } & { [K in keyof OagHorizontalGallery & keyof OagHorizontalGalleryAttributes as `prop:${K}`]?: OagHorizontalGallery[K] };
        "oag-image-comparison": Omit<OagImageComparison, keyof OagImageComparisonAttributes> & { [K in keyof OagImageComparison & keyof OagImageComparisonAttributes]?: OagImageComparison[K] } & { [K in keyof OagImageComparison & keyof OagImageComparisonAttributes as `attr:${K}`]?: OagImageComparisonAttributes[K] } & { [K in keyof OagImageComparison & keyof OagImageComparisonAttributes as `prop:${K}`]?: OagImageComparison[K] };
        "oag-imprint": OagImprint;
        "oag-information": OagInformation;
        "oag-lightbox": Omit<OagLightbox, keyof OagLightboxAttributes> & { [K in keyof OagLightbox & keyof OagLightboxAttributes]?: OagLightbox[K] } & { [K in keyof OagLightbox & keyof OagLightboxAttributes as `attr:${K}`]?: OagLightboxAttributes[K] } & { [K in keyof OagLightbox & keyof OagLightboxAttributes as `prop:${K}`]?: OagLightbox[K] };
        "oag-loading": Omit<OagLoading, keyof OagLoadingAttributes> & { [K in keyof OagLoading & keyof OagLoadingAttributes]?: OagLoading[K] } & { [K in keyof OagLoading & keyof OagLoadingAttributes as `attr:${K}`]?: OagLoadingAttributes[K] } & { [K in keyof OagLoading & keyof OagLoadingAttributes as `prop:${K}`]?: OagLoading[K] };
        "oag-map": Omit<OagMap, keyof OagMapAttributes> & { [K in keyof OagMap & keyof OagMapAttributes]?: OagMap[K] } & { [K in keyof OagMap & keyof OagMapAttributes as `attr:${K}`]?: OagMapAttributes[K] } & { [K in keyof OagMap & keyof OagMapAttributes as `prop:${K}`]?: OagMap[K] };
        "oag-menu": Omit<OagMenu, keyof OagMenuAttributes> & { [K in keyof OagMenu & keyof OagMenuAttributes]?: OagMenu[K] } & { [K in keyof OagMenu & keyof OagMenuAttributes as `attr:${K}`]?: OagMenuAttributes[K] } & { [K in keyof OagMenu & keyof OagMenuAttributes as `prop:${K}`]?: OagMenu[K] };
        "oag-menu-item": OagMenuItem;
        "oag-misc": Omit<OagMisc, keyof OagMiscAttributes> & { [K in keyof OagMisc & keyof OagMiscAttributes]?: OagMisc[K] } & { [K in keyof OagMisc & keyof OagMiscAttributes as `attr:${K}`]?: OagMiscAttributes[K] } & { [K in keyof OagMisc & keyof OagMiscAttributes as `prop:${K}`]?: OagMisc[K] };
        "oag-project": Omit<OagProject, keyof OagProjectAttributes> & { [K in keyof OagProject & keyof OagProjectAttributes]?: OagProject[K] } & { [K in keyof OagProject & keyof OagProjectAttributes as `attr:${K}`]?: OagProjectAttributes[K] } & { [K in keyof OagProject & keyof OagProjectAttributes as `prop:${K}`]?: OagProject[K] };
        "oag-reference": Omit<OagReference, keyof OagReferenceAttributes> & { [K in keyof OagReference & keyof OagReferenceAttributes]?: OagReference[K] } & { [K in keyof OagReference & keyof OagReferenceAttributes as `attr:${K}`]?: OagReferenceAttributes[K] } & { [K in keyof OagReference & keyof OagReferenceAttributes as `prop:${K}`]?: OagReference[K] };
        "oag-screen-background-layer-item": Omit<OagScreenBackgroundLayerItem, keyof OagScreenBackgroundLayerItemAttributes> & { [K in keyof OagScreenBackgroundLayerItem & keyof OagScreenBackgroundLayerItemAttributes]?: OagScreenBackgroundLayerItem[K] } & { [K in keyof OagScreenBackgroundLayerItem & keyof OagScreenBackgroundLayerItemAttributes as `attr:${K}`]?: OagScreenBackgroundLayerItemAttributes[K] } & { [K in keyof OagScreenBackgroundLayerItem & keyof OagScreenBackgroundLayerItemAttributes as `prop:${K}`]?: OagScreenBackgroundLayerItem[K] };
        "oag-screen-content-layer-item": Omit<OagScreenContentLayerItem, keyof OagScreenContentLayerItemAttributes> & { [K in keyof OagScreenContentLayerItem & keyof OagScreenContentLayerItemAttributes]?: OagScreenContentLayerItem[K] } & { [K in keyof OagScreenContentLayerItem & keyof OagScreenContentLayerItemAttributes as `attr:${K}`]?: OagScreenContentLayerItemAttributes[K] } & { [K in keyof OagScreenContentLayerItem & keyof OagScreenContentLayerItemAttributes as `prop:${K}`]?: OagScreenContentLayerItem[K] };
        "oag-screen-map": Omit<OagScreenMap, keyof OagScreenMapAttributes> & { [K in keyof OagScreenMap & keyof OagScreenMapAttributes]?: OagScreenMap[K] } & { [K in keyof OagScreenMap & keyof OagScreenMapAttributes as `attr:${K}`]?: OagScreenMapAttributes[K] } & { [K in keyof OagScreenMap & keyof OagScreenMapAttributes as `prop:${K}`]?: OagScreenMap[K] };
        "oag-tooltip": Omit<OagTooltip, keyof OagTooltipAttributes> & { [K in keyof OagTooltip & keyof OagTooltipAttributes]?: OagTooltip[K] } & { [K in keyof OagTooltip & keyof OagTooltipAttributes as `attr:${K}`]?: OagTooltipAttributes[K] } & { [K in keyof OagTooltip & keyof OagTooltipAttributes as `prop:${K}`]?: OagTooltip[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "oag-application": LocalJSX.IntrinsicElements["oag-application"] & JSXBase.HTMLAttributes<HTMLOagApplicationElement>;
            "oag-audio": LocalJSX.IntrinsicElements["oag-audio"] & JSXBase.HTMLAttributes<HTMLOagAudioElement>;
            "oag-changelog-entry": LocalJSX.IntrinsicElements["oag-changelog-entry"] & JSXBase.HTMLAttributes<HTMLOagChangelogEntryElement>;
            "oag-changelog-version": LocalJSX.IntrinsicElements["oag-changelog-version"] & JSXBase.HTMLAttributes<HTMLOagChangelogVersionElement>;
            "oag-cockpit": LocalJSX.IntrinsicElements["oag-cockpit"] & JSXBase.HTMLAttributes<HTMLOagCockpitElement>;
            "oag-cockpit-navigation-item": LocalJSX.IntrinsicElements["oag-cockpit-navigation-item"] & JSXBase.HTMLAttributes<HTMLOagCockpitNavigationItemElement>;
            "oag-content": LocalJSX.IntrinsicElements["oag-content"] & JSXBase.HTMLAttributes<HTMLOagContentElement>;
            "oag-figure": LocalJSX.IntrinsicElements["oag-figure"] & JSXBase.HTMLAttributes<HTMLOagFigureElement>;
            "oag-font-size": LocalJSX.IntrinsicElements["oag-font-size"] & JSXBase.HTMLAttributes<HTMLOagFontSizeElement>;
            "oag-gallery": LocalJSX.IntrinsicElements["oag-gallery"] & JSXBase.HTMLAttributes<HTMLOagGalleryElement>;
            "oag-hero": LocalJSX.IntrinsicElements["oag-hero"] & JSXBase.HTMLAttributes<HTMLOagHeroElement>;
            "oag-horizontal-gallery": LocalJSX.IntrinsicElements["oag-horizontal-gallery"] & JSXBase.HTMLAttributes<HTMLOagHorizontalGalleryElement>;
            "oag-image-comparison": LocalJSX.IntrinsicElements["oag-image-comparison"] & JSXBase.HTMLAttributes<HTMLOagImageComparisonElement>;
            "oag-imprint": LocalJSX.IntrinsicElements["oag-imprint"] & JSXBase.HTMLAttributes<HTMLOagImprintElement>;
            "oag-information": LocalJSX.IntrinsicElements["oag-information"] & JSXBase.HTMLAttributes<HTMLOagInformationElement>;
            "oag-lightbox": LocalJSX.IntrinsicElements["oag-lightbox"] & JSXBase.HTMLAttributes<HTMLOagLightboxElement>;
            "oag-loading": LocalJSX.IntrinsicElements["oag-loading"] & JSXBase.HTMLAttributes<HTMLOagLoadingElement>;
            "oag-map": LocalJSX.IntrinsicElements["oag-map"] & JSXBase.HTMLAttributes<HTMLOagMapElement>;
            "oag-menu": LocalJSX.IntrinsicElements["oag-menu"] & JSXBase.HTMLAttributes<HTMLOagMenuElement>;
            "oag-menu-item": LocalJSX.IntrinsicElements["oag-menu-item"] & JSXBase.HTMLAttributes<HTMLOagMenuItemElement>;
            "oag-misc": LocalJSX.IntrinsicElements["oag-misc"] & JSXBase.HTMLAttributes<HTMLOagMiscElement>;
            "oag-project": LocalJSX.IntrinsicElements["oag-project"] & JSXBase.HTMLAttributes<HTMLOagProjectElement>;
            "oag-reference": LocalJSX.IntrinsicElements["oag-reference"] & JSXBase.HTMLAttributes<HTMLOagReferenceElement>;
            "oag-screen-background-layer-item": LocalJSX.IntrinsicElements["oag-screen-background-layer-item"] & JSXBase.HTMLAttributes<HTMLOagScreenBackgroundLayerItemElement>;
            "oag-screen-content-layer-item": LocalJSX.IntrinsicElements["oag-screen-content-layer-item"] & JSXBase.HTMLAttributes<HTMLOagScreenContentLayerItemElement>;
            "oag-screen-map": LocalJSX.IntrinsicElements["oag-screen-map"] & JSXBase.HTMLAttributes<HTMLOagScreenMapElement>;
            "oag-tooltip": LocalJSX.IntrinsicElements["oag-tooltip"] & JSXBase.HTMLAttributes<HTMLOagTooltipElement>;
        }
    }
}
